apiVersion: v1
kind: ConfigMap
metadata:
  name: mail-ingestion-config
  namespace: mail-ingestion
data:
  OPENAI_MODEL: "gpt-4o-mini"
  EVENTHUB_NAME: "email-intents"
  GRAPH_CLIENT_STATE: "shreyas-nrt-secret"
